# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GCP Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_ENV: development
  USERS_SERVICE_URL: http://users-service:3000
  MOVIES_SERVICE_URL: http://movies-service:3000
  OMDB_API_KEY: a69b8c8f

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Create network 
      run: docker network create gcloud_example_pipeline

    - name: Builc containers 
      run: docker-compose build

    - name: Run containers 
      run: docker-compose up -d
    
    - name: Network Inspect 
      run: docker ps -a

    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Network Inspect 2
      run: docker ps -a

    - name: Run tests 
      run: |
        cd ./wdio-omdb-automation
        docker-compose run --rm wdio conf/chrome.docker.js